
try:
    pass
    #raise Exception()
except Exception:
    print('Vem aqui se tiver erro')
else:
    print('Vem aqui se n√£o tiver erro')
finally:
    print('Sempre vem aqui')
